name = "emby-proxy-worker"
compatibility_date = "2024-12-01"
main = "src/main.ts"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[durable_objects.bindings]]
name = "WEBSOCKET_PROXY"
class_name = "WebSocketProxy"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketProxy"]
